# Generated by Django 4.0.5 on 2022-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='usernameID',
        ),
        migrations.AddField(
            model_name='customuser',
            name='employer_id',
            field=models.CharField(default='DA900FD', editable=False, max_length=50),
        ),
    ]
