# Generated by Django 4.0.5 on 2022-06-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employer_id',
            field=models.CharField(default='5D2F4E7', editable=False, max_length=50, unique=True),
        ),
    ]
