# Generated by Django 4.0.5 on 2022-06-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_employer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employer_id',
        ),
    ]
