# Generated by Django 4.0.5 on 2022-06-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_employer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='position',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
