# Generated by Django 4.0.5 on 2022-07-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreq',
            name='task_category',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clientreq',
            name='task_service_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
